### ISSUE TITLE
Copy overlay before running fixups

### ISSUE THREAD

**Issue by vaonet-jks** [tobetter/odroid-stamper#8] opened 2021-04-12 15:30 UTC
Copy overlay files before running fixups. This is to help install files that are not part of a package. Source files are copied to a temp directory as part of overlay and a fixup can install them, create symbolic links, etc. Temp directory is deleted by fixup once done.

**Comment by tobetter** [comment] 2021-04-13 08:11
Files in overlay/ directory are copied prior to run the script in fixup/ already.
https://github.com/tobetter/odroid-stamper/blob/master/functions#L335
https://github.com/tobetter/odroid-stamper/blob/master/functions#L419

Can you please check them again?

**Comment by vaonet-jks** [comment] 2021-04-13 13:03
You are correct! I am sorry.

**Comment by tobetter** [comment] 2021-04-13 15:07
So...let me close this since you confirmed. :)

**Closed as completed by tobetter** 2021-04-13 15:07 UTC
